hyperweb-io/starship

- charts/devnet/templates/chain/genesis.yaml
- charts/devnet/templates/chain/validator.yaml
Previously we only created validators with `mnemonic` stored in the `keys.json`
Now if new validators spin up beyond the listed mnemonic, we just create new ones with random mnemonics
> Allow arbitary number of validators

- proto/exposer/genesis.proto
Fix the genesis state of exposer. replace consensus_params to be a generic `google.protobuf.Struct` instead of specific
> hotfix: exposer genesis state update

- .github/actions/e2e-test/action.yaml
- .github/workflows/pr-tests.yaml
- .github/workflows/smoke-tests.yaml
- charts/devnet/templates/chains/cosmos/configmap.yaml
- charts/devnet/templates/chains/cosmos/genesis.yaml
- charts/devnet/values.yaml
- tests/e2e/Makefile
- tests/e2e/config.go
- tests/e2e/configs/one-chain.yaml
- tests/e2e/e2e_test.go
Add `genesis` directive that can override the `genesis.json` file after initial creation of the genesis file.
* Specify the `genesis` directive in the config file
* Create a configmap based on the patch, convert yaml to json
* Apply the patch with `jq -s '.[0] * .[1]' genesis.json patch.json`
```yaml
chains:
- name: osmosis-1
type: osmosis
numValidators: 1
genesis:
app_state:
staking:
params:
unbonding_time: "5s"
gamm:
params:
pool_creation_fee:
- amount: "500000"
denom: uosmo
```
> genesis directive for patching `genesis.json`

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/e2e-tests.yaml
- .github/workflows/lint-check.yaml
- .github/workflows/pr-e2e-tests.yaml
- .github/workflows/pr-tests.yaml
- .github/workflows/smoke-tests.yaml
- .github/workflows/starship-docker.yaml
Add concurrency to each of the workflows, with cancel-in-progress to true.
Too many workflows seem to be running even for the PRs. Reduce the action runner time by fast forwarding cancel.
Note: Sometimes for debuging `cancel-in-progress` might hinder, can be removed tmp per case
> Concurrency for each gh-action

- charts/devnet/defaults.yaml
- charts/devnet/templates/_helpers.tpl
- charts/devnet/templates/relayers/hermes/configmap.yaml
- docker/relayers/hermes/versions.yaml
- docs/pages/config/relayers.mdx
- tests/e2e/configs/two-chain.yaml
* add `event_source` to hermes config to allow pull or push mode (default: push)
* update two-chain e2e test
* set config based on version of hermes from tag
Closes: #153
> Support for hermes 1.6.0, `event_source` to pull or push via config

- .github/workflows/starship-docker.yaml
- charts/devnet/Chart.yaml
- charts/devnet/values.yaml
- docs/pages/config/chains.mdx
- docs/pages/config/features.mdx
* Release 0.1.46-rc2
* Fix `registry.image` to the latest image from docker
* Add docs for `registry.localhost`
> rc release: 0.1.46-rc2, fix registry service image, add docs

- tests/e2e/config.go
- tests/e2e/configs/injective.yaml
- tests/e2e/configs/multi-validator.yaml
- tests/e2e/configs/one-chain-custom-scripts.yaml
- tests/e2e/configs/one-chain.yaml
- tests/e2e/configs/one-custom-chain.yaml
- tests/e2e/configs/simapp.yaml
- tests/e2e/faucet_test.go
- tests/e2e/go.mod
Test to check `/status` and `/credit` for faucets.
Closes: #228
> faucet tests in e2e

- charts/devnet/scripts/update-config.sh
- charts/devnet/templates/chains/cosmos/genesis.yaml
- charts/devnet/templates/chains/cosmos/validator.yaml
- charts/devnet/values.schema.json
- tests/e2e/configs/one-chain.yaml
- tests/e2e/configs/scripts/update-custom-config.sh
To be able to use Starship in production, it needs to have controls to enable metrics supported by Cosmos chains.
Additionally, split genesis and config generation into separate steps.
> Add metrics support to Cosmos chains

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint-check.yaml
- .github/workflows/pr-tests.yaml
Do not run gh-actions on PRs in draft. Needed to make it explicit.
> chore: add conditions to not run PRs on draft PRs

- charts/devnet/Chart.yaml
- charts/devnet/templates/_helpers.tpl
- charts/devnet/templates/explorer.yaml
- charts/devnet/templates/ingress/cert-issuer.yaml
- charts/devnet/templates/ingress/ingress.yaml
- charts/devnet/values.schema.json
- charts/devnet/values.yaml
Closes: #8 
Note: This presumes that both the controller for `ingress` and `cert-issuer` are pre-installed. 
Maybe we need to figure out a way to install them with the helm chart itself
> feature: `ingress` directive in config file

- docs/pages/config/chains.mdx
- docs/pages/config/index.mdx
- docs/pages/get-started/step-3.mdx
- starship/charts/devnet/defaults.yaml
- starship/charts/devnet/values.schema.json
- starship/tests/e2e/configs/agoric.yaml
- starship/tests/e2e/configs/build-chain.yaml
- starship/tests/e2e/configs/evmos.yaml
- starship/tests/e2e/configs/injective.yaml
- starship/tests/e2e/configs/multi-relayer.yaml
- starship/tests/e2e/configs/neutron.yaml
- starship/tests/e2e/configs/one-chain-cometmock.yaml
- starship/tests/e2e/configs/three-chain.yaml
- starship/tests/e2e/configs/two-chain-cometmock.yaml
- starship/tests/e2e/configs/two-chain-gorelayer.yaml
- starship/tests/e2e/configs/two-chain-monitoring.yaml
- starship/tests/e2e/configs/two-chain.yaml
- starship/tests/smoke/ci/osmojs.yaml
In starship we had named cosmoshub chain as cosmos. To match the standards followed in chain-registry, we are changing it to cosmoshub.
Will be part of the next chart release and only v2.
> chore: rename cosmos to cosmoshub

- docs/pages/config/chains.mdx
- starship/charts/devnet/templates/chains/cosmos/genesis.yaml
- starship/charts/devnet/templates/chains/cosmos/validator.yaml
- starship/charts/devnet/values.schema.json
- starship/charts/devnet/values.yaml
- adds `env` to chain directive syntax to support custom environment variables in the `genesis` and `validator` containers
> feat: add chain directive for `env`

- clients/js/packages/cli/src/utils.ts
- clients/js/packages/client/src/client.ts
> feature: add namespace to starshipjs

- clients/js/packages/client/src/client.ts
- clients/js/packages/client/src/config.ts
Starship cli was missing some features from the older `install.sh`.
Handling custom chain scripts is one of them.
Runs locally now.
> feature: add scripts to args for install

- clients/js/README.md
- clients/js/packages/starshipjs/README.md
- clients/js/packages/starshipjs/__tests__/config.test.ts
- clients/js/packages/starshipjs/__tests__/legacy.test.ts
- clients/js/packages/starshipjs/src/config.ts
- clients/js/packages/starshipjs/src/hooks.ts
add init for config context, support legacy usage
test and fixed docs
Posting this PR is for more clear error message when config is not properly initialized.
(There's not error message if config and registry're not set.)
And backward compitablity is supported, meaning the old way of setting config is still available but not recommended.
> add init for config context, support legacy usage

- .github/workflows/e2e-tests.yaml
- .github/workflows/pr-tests.yaml
- starship/charts/devnet/Chart.yaml
- starship/charts/devnet/defaults.yaml
- starship/tests/e2e/configs/one-cosmoshub-starship-faucet.yaml
> bugfix: add test for running cosmoshub and starship faucet

- clients/js/packages/client/src/client.ts
> add pod statuses as a struct, add RunningButNotReady state

- docs/pages/get-started/step-2.mdx
> docs: remove kind from setup setps

- examples/cosmos-simapp-multi/scripts/port-forward.sh
- examples/getting-started/scripts/port-forward.sh
- examples/injective/scripts/port-forward.sh
- examples/multi-chain/scripts/port-forward.sh
- examples/neutron/scripts/port-forward.sh
- examples/osmojs/scripts/port-forward.sh
- starship/scripts/port-forward.sh
- if custom ports are provided in config.yaml, the port-forward script did not recognize them
- aiming to have this in [cosmology-tech/starship-action](https://github.com/cosmology-tech/starship-action), which may require a release
> fix: respect custom registry and explorer ports

- clients/js/packages/client/src/client.ts
> fix: remove pods from checking status, if they are no longer found, update default chart version

- clients/js/packages/client/src/client.ts
- feat(client): expose `restartThreshold` via `StarshipContext`
- allow api consumers to specify `restartThreshold` > default value of 3
Context: with the faucet enabled, the agoric pod experiences up to 5 restarts (perhaps the faucet doesn't respect the validator's readiness check?). This change would allow us to use the latest versions of starship in CI.
> feat(client): expose `restartThreshold` via `StarshipContext`

- .github/workflows/pr-tests.yaml
- starship/charts/devnet/defaults.yaml
- starship/charts/devnet/templates/chains/cosmos/genesis.yaml
- starship/faucet/distributor.go
- starship/tests/e2e/faucet_test.go
> fix: remove after log, no longer required, nor is it actually correct

- clients/js/packages/client/src/client.ts
- clients/js/packages/client/src/config.ts
- docs/pages/config/chains.mdx
- docs/pages/config/ethereum.mdx
- starship/charts/devnet/values.schema.json
> fix: expose ws for eth chain from client, update docs to point to ws, update schema

- starship/scripts/install.sh
When a chain config a `scripts` property after another that did not, it would omit the arg, resulting in a validation error installing the config.
This makes it iterate over all the chains to get the correct arguments.
> fix: non-consecutive config scripts

- docs/config/chains.mdx
- starship/charts/devnet/defaults.yaml
- starship/charts/devnet/scripts/default/chain-rpc-ready.sh
- starship/charts/devnet/templates/chains/cosmos/genesis.yaml
- starship/charts/devnet/templates/chains/cosmos/validator.yaml
- starship/charts/devnet/values.schema.json
- starship/charts/devnet/values.yaml
This PR consolidates all the different ways of checking if a chain node's RPC service is ready to use.
Documentation, scripts, and examples have been updated accordingly.
The Agoric `readinessProbe` now just uses the defaults.  I've verified that properly waiting for RPC to become ready (instead of restarting the pod's faucet and hitting backoff) has reduced the time needed to boot up `agoriclocal-genesis-0` on my machine from 14 minutes down to 6 minutes.
> feat: add and use `chain.scripts.chainRpcReady`

- .github/workflows/build.yaml
- .github/workflows/docker.yaml
- .github/workflows/lint-check.yaml
- .github/workflows/lint-client.yml
- .github/workflows/pr-tests.yaml
- .github/workflows/run-client-tests.yml
- .github/workflows/starship-docker.yaml
- starship/charts/devnet/Chart.yaml
- starship/charts/devnet/templates/_helpers.tpl
- starship/charts/devnet/templates/chains/cosmos/genesis.yaml
- starship/charts/devnet/templates/chains/cosmos/validator.yaml
This PR allows parameterisation of a `config.yaml`'s 'chain[*].scripts', by passing `chain[*].env` environment variables wherever those scripts are invoked.  This apparently already worked for `$CHAIN_ID`, but not for any other of the config.yaml's environment variables.  There may be an even simpler way to accomplish it, so I am happy for any feedback you can suggest, @Anmol1696.
Before this change, some scripts that we override (`update-config.sh` for our particular use in [Agoric/agoric-sdk#11502](https://github.com/Agoric/agoric-sdk/pull/11502#issuecomment-2991200809)) would have to be manually copied-and-pasted with modifications, or generated from a template in order to have different behaviour when used in different `config.yaml` files but also with the same `$CHAIN_ID`.
Credit to …
> feat(cosmos): propagate `$chain.env` when calling scripts
