charts/devnet/values.schema.json, charts/devnet/values.yaml
=> Initial json schema for values

charts/devnet/templates/_helpers.tpl, charts/devnet/templates/chain/genesis.yaml, charts/devnet/templates/chain/validator.yaml, charts/devnet/values.yaml, examples/Makefile, registry/BUILD.bazel, registry/Makefile
Fix the helm charts to adapt for the new exposer
Also part of #37, since increasing the resources for the init containers to have faster key addition step.
=> Exposer fix

Makefile, examples/Makefile, scripts/common.sh, scripts/port-forward.sh, scripts/update-go-pbs.sh
=> Script port-forward

BUILD.bazel, README.md, WORKSPACE, collector/BUILD.bazel, demo.md, exposer/BUILD.bazel, exposer/app.go, exposer/go.mod, exposer/handler.go, proto/buf.gen.yaml, proto/exposer/BUILD.bazel, proto/exposer/genesis.proto, proto/exposer/mnemonic.proto, proto/exposer/service.proto, proto/registry/BUILD.bazel, proto/registry/chain.proto, proto/registry/ibc.proto, proto/registry/service.proto, registry/BUILD.bazel, registry/app.go, registry/chain.go, registry/go.mod, registry/handler.go, registry/model.go
Change `Anmol1696/` to `cosmology-tech`
=> fix repo name

.github/workflows/e2e-tests.yaml
=> Run e2e tests on remote AWS cluster

.github/actions/e2e-test/action.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/pr-e2e-tests.yaml
Move e2e tests to custom composite action, use action with strategy matrix for e2e tests, add pr-e2e test to run e2e on a PR comment
=> update e2e test gh-action

.github/workflows/e2e-tests.yaml, .github/workflows/pr-e2e-tests.yaml, .github/workflows/pr-tests.yaml, charts/devnet/templates/chain/genesis.yaml, charts/devnet/templates/chain/validator.yaml, charts/devnet/templates/explorer.yaml, charts/devnet/templates/registry.yaml, charts/devnet/templates/relayers/hermes/configmap.yaml, charts/devnet/templates/relayers/ts-relayer/configmap.yaml, tests/configs/one-custom-chain.yaml
=> merge default chain into chain while reading looking for user values

docs/docs/tutorial/step-1.md, docs/docs/tutorial/step-2.md, docs/docs/tutorial/step-3.md, docs/docs/tutorial/step-4.md, examples/getting-started/Makefile, examples/getting-started/README.md, examples/getting-started/configs/starship.yaml, examples/getting-started/configs/tiny-starship.yaml, examples/getting-started/scripts/dev-setup.sh, examples/getting-started/scripts/port-forward.sh
=> Docs tutorial Getting started

charts/devnet/scripts/setup_config.sh, charts/devnet/scripts/setup_genesis.sh
remove dependence on -z in sed, use line specific changes with sed, update grpc address and enable server.
Closes #116
=> Update grpc config.sh

charts/devnet/Chart.yaml, charts/devnet/templates/explorer.yaml, examples/getting-started/Makefile, examples/multi-chain/Makefile, examples/multi-chain/config.yaml, examples/osmojs/Makefile
fix explorer to use correct path and host, update chart to 0.1.34, update all examples to use 0.1.34 chart version
=> Fix explorer, upgrade chart to 0.1.34

.github/workflows/docker.yaml, docker/chains/versions.yaml
* Add simapp chain version
* update docker workflow to build docker images on PR, not push though
=> Simaap docker

.github/workflows/docker.yaml, charts/devnet/Chart.yaml, charts/devnet/values.yaml, docker/chains/build-docker-chains.sh, docker/chains/versions.yaml, docker/explorers/ping-pub/Dockerfile, docker/explorers/ping-pub/versions.yaml, docker/faucet/cosmjs-faucet/Dockerfile, docker/faucet/cosmjs-faucet/versions.yaml, docker/relayers/hermes/versions.yaml, docs/pages/get-started/step-3.mdx, examples/cosmos-simapp-multi/Makefile, examples/getting-started/Makefile, examples/multi-chain/Makefile, examples/osmojs/Makefile, scripts/build-docker.sh
=> Build with platform arm

charts/devnet/templates/_helpers.tpl, charts/devnet/templates/chain/genesis.yaml, charts/devnet/templates/chain/validator.yaml, charts/devnet/templates/collector.yaml, charts/devnet/templates/explorer.yaml, charts/devnet/templates/registry.yaml, charts/devnet/templates/relayers/hermes/statefulset.yaml, charts/devnet/templates/relayers/ts-relayer/statefulset.yaml, charts/devnet/values.yaml, examples/cosmos-simapp-multi/configs/devnet-30.yaml, examples/cosmos-simapp-multi/configs/local-custom.yaml, examples/cosmos-simapp-multi/configs/local.yaml, examples/getting-started/configs/tiny-starship.yaml, examples/upgrade-test/config.yaml, tests/configs/build-chain.yaml, tests/configs/multi-validator.yaml, tests/configs/one-chain.yaml, tests/configs/one-custom-chain.yaml, tests/configs/two-chain.yaml
Optionally support full resource object as well, update all examples and tests
Closes #133
=> Update resource directive to use directly cpu and memory

.github/workflows/pr-tests.yaml, charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/templates/chains/cosmos/validator.yaml, charts/devnet/values.yaml, docs/pages/config/chains.mdx, tests/configs/multi-validator.yaml, tests/configs/one-chain.yaml
=> feature: add faucet.concurrency directive, add to tests

docker/chains/versions.yaml
Adding the latest version of cheqd and neutron
=> update: add more chains from heighliner

charts/devnet/defaults.yaml, docker/relayers/go-relayer/Dockerfile, docker/relayers/go-relayer/versions.yaml, tests/e2e/configs/two-chain-gorelayer.yaml
=> add docker for go-relayer

.github/workflows/e2e-tests.yaml, .github/workflows/pr-e2e-tests.yaml, .github/workflows/pr-tests.yaml, charts/devnet/scripts/update-config.sh, charts/devnet/scripts/update-genesis.sh, charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/templates/explorer.yaml, charts/devnet/templates/registry.yaml, charts/devnet/templates/relayers/go-relayer/statefulset.yaml, charts/devnet/templates/relayers/hermes/statefulset.yaml, charts/devnet/templates/relayers/ts-relayer/statefulset.yaml, examples/upgrade-test/setup_test.go, tests/e2e/configs/simapp.yaml, tests/e2e/e2e_test.go, tests/e2e/exposer_test.go, tests/e2e/go.mod, tests/e2e/registry_test.go
We make Starship helm charts work seamlessly with sdk 47
Additionally add tests to run latest simapp as part of Starship e2e tests.
=> cosmos-sdk 47 compatible

charts/devnet/values.schema.json, scripts/install.sh, tests/e2e/Makefile
Closes: #12 
* Create schema file for values.yaml and config files
* Fix `install.sh` script
* Use install script for e2e tests makefile
=> initial values schema.json file, with chains working

charts/devnet/templates/_helpers.tpl, charts/devnet/templates/registry.yaml, charts/devnet/values.schema.json, charts/devnet/values.yaml, registry/Makefile, registry/config.go, registry/handler.go, tests/e2e/registry_test.go
Closes: #213
By default we set localhost to true.
=> feature: add `registry.locahost` for setting rpc, grpc and rest addresses

cmd/starship/charts.go, cmd/starship/config.go, cmd/starship/main.go, cmd/starship/root.go
=> feature: starship cli update

charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/values.schema.json, charts/devnet/values.yaml
=> add faucet.enabled param

.github/workflows/e2e-tests.yaml, .github/workflows/pr-e2e-tests.yaml, .github/workflows/pr-tests.yaml, charts/devnet/defaults.yaml, charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/values.schema.json, docs/pages/config/chains.mdx, tests/e2e/configs/evmos.yaml, tests/e2e/configs/injective.yaml, tests/e2e/configs/multi-validator-starship-faucet.yaml, tests/e2e/configs/one-chain-starship-faucet.yaml, tests/e2e/faucet_test.go
=> feature: add support for starship-faucet in helm, add tests

charts/devnet/templates/_helpers.tpl, charts/devnet/templates/relayers/go-relayer/configmap.yaml, charts/devnet/templates/relayers/go-relayer/statefulset.yaml, charts/devnet/templates/relayers/hermes/configmap.yaml, charts/devnet/templates/relayers/hermes/statefulset.yaml, charts/devnet/templates/relayers/ts-relayer/configmap.yaml, charts/devnet/templates/relayers/ts-relayer/statefulset.yaml
Reverts cosmology-tech/starship#256
=> Revert "chore: add and use template function to evaluate fullchain dict from just the name, used in all relayers"

README.md, docs/pages/config/chains.mdx, docs/pages/config/features.mdx, docs/pages/config/index.mdx, docs/pages/get-started/step-1.mdx, docs/pages/get-started/step-3.mdx, docs/pages/get-started/step-5.mdx, docs/pages/index.mdx
=> fix: typos

charts/devnet/scripts/update-config.sh, charts/devnet/templates/_chains.tpl, charts/devnet/templates/_helpers.tpl, charts/devnet/templates/chains/cosmos/configmap.yaml, charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/templates/chains/cosmos/service.yaml, charts/devnet/templates/chains/cosmos/validator.yaml, charts/devnet/templates/explorer.yaml, charts/devnet/templates/registry.yaml, charts/devnet/templates/relayers/go-relayer/configmap.yaml, charts/devnet/templates/relayers/go-relayer/statefulset.yaml, charts/devnet/templates/relayers/hermes/configmap.yaml, charts/devnet/templates/relayers/hermes/statefulset.yaml, charts/devnet/templates/relayers/ts-relayer/configmap.yaml, charts/devnet/templates/relayers/ts-relayer/statefulset.yaml
Create template functions to create chain directive which will setup default settings as well as reduce overhead templates on multiple yaml files.
=> helm beutification

.github/workflows/starship-docker.yaml, exposer/Makefile
=> fix: add check to run all steps in conditions

charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/templates/chains/cosmos/validator.yaml, exposer/config.go, exposer/handler.go, tests/e2e/configs/build-chain.yaml, tests/e2e/configs/evmos.yaml, tests/e2e/configs/injective.yaml, tests/e2e/configs/multi-validator-starship-faucet.yaml, tests/e2e/configs/multi-validator.yaml, tests/e2e/configs/one-chain-custom-scripts.yaml, tests/e2e/configs/one-chain-starship-faucet.yaml, tests/e2e/configs/one-chain.yaml, tests/e2e/configs/one-custom-chain.yaml, tests/e2e/configs/simapp.yaml, tests/e2e/configs/two-chain-gorelayer.yaml, tests/e2e/configs/two-chain.yaml
=> feature: update node_id handler to read from file instead of status

charts/devnet/templates/_helpers.tpl, charts/devnet/templates/chains/cosmos/cometmock.yaml, charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/templates/chains/cosmos/validator.yaml, charts/devnet/templates/explorer.yaml, charts/devnet/templates/registry.yaml, charts/devnet/templates/relayers/go-relayer/statefulset.yaml, charts/devnet/templates/relayers/hermes/statefulset.yaml, charts/devnet/templates/relayers/ts-relayer/statefulset.yaml, charts/devnet/values.schema.json, charts/devnet/values.yaml
=> chore: use global image pull policy, instead of Always, set default to IfNotPresent

.github/actions/e2e-test/action.yaml, .github/workflows/build.yaml, .github/workflows/pr-tests.yaml, .github/workflows/smoke-tests.yaml, clients/go/client/go.mod, cmd/starship/go.mod, docker/chains/Dockerfile, docker/chains/Dockerfile.injective, docker/chains/Dockerfile.union, docker/faucet/cosmjs-faucet/Dockerfile, docker/relayers/go-relayer/Dockerfile, docker/starship/base/Dockerfile, docker/starship/base/Dockerfile.arm64, docker/starship/builder/Dockerfile, docker/starship/runner/Dockerfile, examples/upgrade-test/go.mod, exposer/Dockerfile, exposer/go.mod, exposer/go.sum, faucet/Dockerfile, faucet/go.mod, go.work, registry/Dockerfile, registry/go.mod, tests/e2e/go.mod, tools/go.mod
=> chore: upgrade from go 1.19 to go 1.21 everywhere

charts/devnet/Chart.yaml, charts/devnet/templates/relayers/hermes/configmap.yaml
Closes: #402 
Add initial code to extract chain config from config directive
=> feature: chain config from `relayer.config` for hermes

.github/workflows/e2e-tests.yaml, .github/workflows/pr-e2e-tests.yaml, charts/devnet/Chart.yaml, charts/devnet/templates/_relayers.tpl, charts/devnet/templates/relayers/hermes/configmap.yaml, charts/devnet/templates/relayers/hermes/statefulset.yaml, charts/devnet/values.schema.json, charts/devnet/values.yaml, tests/e2e/configs/three-chain.yaml
Closes: #139
Be able to specify paths between chains to be initialized during setup.
=> feature: `channels` directive in `relayers`

charts/devnet/defaults.yaml
=> fix: update default neutron version to be 2.0.1

.github/workflows/e2e-tests.yaml, .github/workflows/pr-e2e-tests.yaml, charts/devnet/defaults.yaml, charts/devnet/scripts/default/create-validator.sh, charts/devnet/templates/chains/cosmos/cometmock.yaml, charts/devnet/templates/chains/cosmos/genesis.yaml, charts/devnet/templates/chains/cosmos/validator.yaml, charts/devnet/values.schema.json, tests/e2e/configs/agoric.yaml
Apart from adding agoric chain, we also add a bunch of rediness probes for validator nodes all across, this helps with readiness state and reduces faslse positives as well.
=> chore: add agoric chain

.github/workflows/smoke-tests.yaml
=> hotfix: fix typo in smoke tests

starship/docker/chains/versions.yaml
=> chore: add dym chain docker images

starship/charts/devnet/scripts/default/build-chain.sh
Ensures commit hashes and all git tags are supported as mentioned here:
https://github.com/cosmology-tech/starship/blob/3bcd70ac6975b600c9beec3cf0f709940ac75cb3/docs/pages/config/chains.mdx?plain=1#L189
=> feat(build-chain): support commit hashes and tags that do not start with `v`

clients/js/packages/client/src/client.ts
This PR aims at adding GRPC port-forward.
Closes https://github.com/cosmology-tech/starship/issues/477
=> Add GRPC port-forward

clients/js/packages/client/src/client.ts
=> hotfix: add check for each container readyness check as well

starship/charts/devnet/templates/chains/cosmos/genesis.yaml, starship/faucet/distributor.go, starship/tests/e2e/configs/simapp.yaml
=> fix: start to fix the faucet for balances

clients/js/packages/client/src/client.ts
=> chore: add formatChainID function

starship/docker/chains/versions.yaml
=> chore: add kujira docker support

starship/charts/devnet/templates/relayers/ts-relayer/configmap.yaml
=> fix ident of ts-relayer

clients/js/packages/client/src/client.ts
=> fix: cli pre checks

clients/js/packages/client/src/client.ts
=> feature: add error handling in exec command

starship/charts/devnet/templates/chains/cosmos/genesis.yaml, starship/charts/devnet/templates/chains/cosmos/validator.yaml
=> feature: change readinessprobe to be exec command to check sync info status

starship/charts/devnet/templates/chains/cosmos/genesis.yaml, starship/charts/devnet/values.schema.json, starship/tests/e2e/config.go, starship/tests/e2e/configs/one-chain.yaml, starship/tests/e2e/e2e_test.go
=> feature: add balances section in config

clients/js/packages/client/src/client.ts, clients/js/packages/client/src/config.ts, starship/charts/devnet/scripts/default/update-config.sh, starship/charts/devnet/templates/chains/cosmos/service.yaml, starship/charts/devnet/values.schema.json, starship/scripts/port-forward.sh, starship/tests/e2e/configs/one-chain.yaml
=> feature: start to expose grpc web to config and beyond

docs/pages/config/chains.mdx, starship/charts/devnet/Chart.yaml, starship/charts/devnet/defaults.yaml, starship/charts/devnet/templates/chains/cosmos/genesis.yaml, starship/charts/devnet/templates/chains/cosmos/validator.yaml, starship/charts/devnet/values.schema.json
=> feature: expose readinessProbe to the config file for chain, add to doc, fix readinessProbe

starship/docker/chains/versions.yaml
=> docker: add noble chain

starship/charts/devnet/defaults.yaml, starship/charts/devnet/values.schema.json, starship/docker/chains/versions.yaml
Add noble chain.
Part of: #566 
Note: Noble chain still might not start due to issues with updating the `genesis.json` file.
=> feature: noble helm chart support

starship/charts/devnet/defaults.yaml, starship/charts/devnet/scripts/noble/create-genesis.sh, starship/charts/devnet/scripts/noble/update-genesis.sh
closes: #566
See 4ad3cb7 for a diff against the default genesis scripts.
=> feat: noble custom genesis

clients/js/packages/cli/src/index.ts, clients/js/packages/cli/src/utils.ts, clients/js/packages/client/__tests__/__snapshots__/client.config.test.ts.snap, clients/js/packages/client/__tests__/__snapshots__/client.ports.test.ts.snap, clients/js/packages/client/__tests__/__snapshots__/client.test.ts.snap, clients/js/packages/client/src/client.ts
=> feature: add `waitForPodsTerminating` on stop command, update related cli and test

starship/registry/chain.go
=> chore: fix function name in comment

starship/docker/chains/Dockerfile.eth-beacon, starship/docker/chains/Dockerfile.eth-prysmctl, starship/docker/chains/Dockerfile.eth-validator, starship/docker/chains/versions.yaml
=> docker: update docker files for prysm docker files

starship/docker/chains/versions.yaml
https://github.com/strangelove-ventures/heighliner/pkgs/container/heighliner%2Fstride/348696356?tag=v25.1.0
=> chore: add `stride@v25.1.0` chain image

starship/registry/chain.go
=> chore: fix comment

docs/pages/cli/index.mdx
=> docs: update basic usage of starship-cli

.github/workflows/docker.yaml
=> feature: only login into docker if we need to push the image

starship/charts/devnet/defaults.yaml, starship/charts/devnet/scripts/evm/update-genesis.sh, starship/charts/devnet/values.schema.json, starship/docker/chains/versions.yaml
- Script support for all chains using [evm](https://github.com/cosmos/evm)
- support XPLA Chain
=> feat: support cosmos/evm chain

.github/workflows/lint-client.yml, .github/workflows/run-client-tests.yml, clients/js/packages/client/src/installer.ts
=> fix: add an end statement to the install command

.github/workflows/pr-tests.yaml, starship/charts/devnet/Chart.yaml, starship/charts/devnet/values.yaml, starship/tests/e2e/configs/one-chain-cosmjs-faucet.yaml, starship/tests/e2e/configs/one-cosmoshub-cosmjs-faucet.yaml
Make starship the default faucet for starship
=> release: new release 1.6.0

clients/js/packages/client/src/client.ts
=> fix: use kubectl args to be passed to stop command

docs/development/add-new-chain.md, starship/charts/devnet/defaults.yaml, starship/docker/chains/Dockerfile.xpla, starship/docker/chains/versions.yaml, starship/tests/e2e/address.go, starship/tests/e2e/configs/xpla.yaml
A fully working `make test HELM_FILE=configs/xpla.yaml` example
=> fix: XPLA Chain

starship/docker/chains/Dockerfile.solana, starship/docker/chains/versions.yaml
=> docker: add solana to docker support of starship

starship/docker/chains/versions.yaml
=> docker: add versions for solana agave

examples/mesh-security/custom-values.yaml, starship/charts/devnet/values.yaml
=> chore: remove redundant words
